obj-$(CONFIG_MXC_KGSL) += mxc_kgsl.o
mxc_kgsl-objs += kgsl_cmdstream.o \
		kgsl_device.o \
		kgsl_drawctxt.o \
		kgsl_driver.o \
		kgsl_g12.o \
		kgsl_g12_cmdstream.o \
		kgsl_g12_cmdwindow.o \
		kgsl_g12_drawctxt.o \
		kgsl_memmgr.o \
		kgsl_mmu.o \
		kgsl_ringbuffer.o \
		kgsl_sharedmem.o \
		kgsl_yamato.o \
		kgsl_linux_map.o \
		kgsl_hal.o \
		kgsl_log.o \
		kgsl_pwrctrl.o \
		kgsl.o \
